# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kostiantyn/Documents/education/C/cyber-pet-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kostiantyn/Documents/education/C/cyber-pet-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostiantyn/Documents/education/C/cyber-pet-project/CMakeFiles /home/kostiantyn/Documents/education/C/cyber-pet-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostiantyn/Documents/education/C/cyber-pet-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cyber_pet_project

# Build rule for target.
cyber_pet_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cyber_pet_project
.PHONY : cyber_pet_project

# fast build rule for target.
cyber_pet_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/build
.PHONY : cyber_pet_project/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/source/Button.o: src/source/Button.cpp.o
.PHONY : src/source/Button.o

# target to build an object file
src/source/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Button.cpp.o
.PHONY : src/source/Button.cpp.o

src/source/Button.i: src/source/Button.cpp.i
.PHONY : src/source/Button.i

# target to preprocess a source file
src/source/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Button.cpp.i
.PHONY : src/source/Button.cpp.i

src/source/Button.s: src/source/Button.cpp.s
.PHONY : src/source/Button.s

# target to generate assembly for a file
src/source/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Button.cpp.s
.PHONY : src/source/Button.cpp.s

src/source/Game.o: src/source/Game.cpp.o
.PHONY : src/source/Game.o

# target to build an object file
src/source/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Game.cpp.o
.PHONY : src/source/Game.cpp.o

src/source/Game.i: src/source/Game.cpp.i
.PHONY : src/source/Game.i

# target to preprocess a source file
src/source/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Game.cpp.i
.PHONY : src/source/Game.cpp.i

src/source/Game.s: src/source/Game.cpp.s
.PHONY : src/source/Game.s

# target to generate assembly for a file
src/source/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Game.cpp.s
.PHONY : src/source/Game.cpp.s

src/source/JSON_API.o: src/source/JSON_API.cpp.o
.PHONY : src/source/JSON_API.o

# target to build an object file
src/source/JSON_API.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/JSON_API.cpp.o
.PHONY : src/source/JSON_API.cpp.o

src/source/JSON_API.i: src/source/JSON_API.cpp.i
.PHONY : src/source/JSON_API.i

# target to preprocess a source file
src/source/JSON_API.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/JSON_API.cpp.i
.PHONY : src/source/JSON_API.cpp.i

src/source/JSON_API.s: src/source/JSON_API.cpp.s
.PHONY : src/source/JSON_API.s

# target to generate assembly for a file
src/source/JSON_API.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/JSON_API.cpp.s
.PHONY : src/source/JSON_API.cpp.s

src/source/Player.o: src/source/Player.cpp.o
.PHONY : src/source/Player.o

# target to build an object file
src/source/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Player.cpp.o
.PHONY : src/source/Player.cpp.o

src/source/Player.i: src/source/Player.cpp.i
.PHONY : src/source/Player.i

# target to preprocess a source file
src/source/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Player.cpp.i
.PHONY : src/source/Player.cpp.i

src/source/Player.s: src/source/Player.cpp.s
.PHONY : src/source/Player.s

# target to generate assembly for a file
src/source/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cyber_pet_project.dir/build.make CMakeFiles/cyber_pet_project.dir/src/source/Player.cpp.s
.PHONY : src/source/Player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cyber_pet_project"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/source/Button.o"
	@echo "... src/source/Button.i"
	@echo "... src/source/Button.s"
	@echo "... src/source/Game.o"
	@echo "... src/source/Game.i"
	@echo "... src/source/Game.s"
	@echo "... src/source/JSON_API.o"
	@echo "... src/source/JSON_API.i"
	@echo "... src/source/JSON_API.s"
	@echo "... src/source/Player.o"
	@echo "... src/source/Player.i"
	@echo "... src/source/Player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

